INSERT INTO table_col (id, col, row, value)
VALUES  (1, 1, 1, 'Armoring'),
        (1, 2, 1, 'Security, Survival, Technology'),
        (1, 1, 2, 'Ground Vehicle Dynamics'),
        (1, 2, 2, 'Drive, Technology'),
        (1, 1, 3, 'Psychology'),
        (1, 2, 3, 'Appeal, Commerce, Deceive, Interrogation'),
        (1, 1, 0, 'Education'),
        (1, 2, 0, 'Example Skills'),
        (2, 1, 0, 'Name'),
        (2, 2, 0, 'Hit'),
        (2, 3, 0, 'MS'),
        (2, 4, 0, 'Example'),
        (2, 1, 1, 'Miniscule'),
        (2, 2, 1, '-40'),
        (2, 3, 1, '-4'),
        (2, 4, 1, 'a knife, pistol, or mobile phone'),
        (2, 1, 2, 'Puny'),
        (2, 2, 2, '-20'),
        (2, 3, 2, '-2'),
        (2, 4, 2, 'a limb, rifle or sword'),
        (2, 1, 3, 'Tiny'),
        (2, 2, 3, '-10'),
        (2, 3, 3, '-1'),
        (2, 4, 3, 'a child'),
        (2, 1, 4, 'Small'),
        (2, 2, 4, '-5'),
        (2, 3, 4, '-0.5'),
        (2, 4, 4, 'small people, tall children'),
        (2, 1, 5, 'Average'),
        (2, 2, 5, '-'),
        (2, 3, 5, '-'),
        (2, 4, 5, 'most humans'),
        (2, 1, 6, 'Tall'),
        (2, 2, 6, '+5'),
        (2, 3, 6, '+0.5'),
        (2, 4, 6, 'imposing vat-grown soldiers and bodyguards'),
        (2, 1, 7, 'Huge'),
        (2, 2, 7, '+10'),
        (2, 3, 7, '+1'),
        (2, 4, 7, 'horses, bikes'),
        (2, 1, 8, 'Hulking'),
        (2, 2, 8, '+20'),
        (2, 3, 8, '+2'),
        (2, 4, 8, 'cars'),
        (2, 1, 9, 'Enormous'),
        (2, 2, 9, '+40'),
        (2, 3, 9, '+4'),
        (2, 4, 9, 'buses, trucks'),
        (3, 1, 0, 'Material'),
        (3, 2, 0, 'Armor per cm'),
        (3, 1, 1, 'Light: Wood, Plastic'),
        (3, 2, 1, '2'),
        (3, 1, 2, 'Medium: Glass, Soil'),
        (3, 2, 2, '5'),
        (3, 1, 3, 'Heavy: Concrete, Steel'),
        (3, 2, 3, '8'),
        (4, 1, 0, 'Location'),
        (4, 2, 0, 'HP'),
        (4, 3, 0, 'Random'),
        (4, 1, 1, 'Head'),
        (4, 2, 1, '15'),
        (4, 3, 1, '1-10'),
        (4, 1, 2, 'Right Arm'),
        (4, 2, 2, '15'),
        (4, 3, 2, '11-25'),
        (4, 1, 3, 'Left Arm'),
        (4, 2, 3, '15'),
        (4, 3, 3, '26-40'),
        (4, 1, 4, 'Body'),
        (4, 2, 4, '25'),
        (4, 3, 4, '41-70'),
        (4, 1, 5, 'Right Leg'),
        (4, 2, 5, '15'),
        (4, 3, 5, '71-85'),
        (4, 1, 6, 'Left Leg'),
        (4, 2, 6, '15'),
        (4, 3, 6, '86-100'),
        (5, 1, 0, 'DoF + D10'),
        (5, 2, 0, 'Result'),
        (5, 1, 1, '1-3'),
        (5, 2, 1, 'Shivering, the character takes a -10 penalty on his tests until he passes a courage check. He can spend one action to attempt this check.'),
        (5, 1, 2, '4-5'),
        (5, 2, 2, 'Severely shaken, the character takes a -15 penalty on all tests for the rest of the encounter or scene and can’t use maneuvers or transform actions.'),
        (5, 1, 3, '6-7'),
        (5, 2, 3, 'Dumbstruck by fear, the character freezes in place and can’t act until he passes a courage check at the end of one of his turns. This check begins at the same penalty as the initial one and gets a cumulative +10 for every previous attempt. He may take reactions to defend himself or run away (at an increased risk of stumbling as quickly avoiding obstacles is "acting"...)'),
        (5, 1, 4, '8-9'),
        (5, 2, 4, 'Frozen by terror, the character is completely unable to move until he passes a courage check at the end of one of his turns. This check begins at the same penalty as the initial one and gets a cumulative +5 for every previous attempt. Courage checks are allowed 1D5-1 rounds after fear strikes. He may take reactions to defend himself.'),
        (5, 1, 5, '10-11'),
        (5, 2, 5, 'Overcome by horror, the character loses consciousness for 1D10-CrB minutes, minimum of 1.'),
        (5, 1, 6, '12-13'),
        (5, 2, 6, 'Pure horror pierces the character’s heart. His courage is reduced by 2D10+5 for a week, recovering by 1 each day afterwards. He takes a second shock effect at a value of D100/2.'),
        (5, 1, 7, '14-15'),
        (5, 2, 7, 'Stuck in their worst nightmare, the character falls comatose for a day.'),
        (5, 1, 8, '16-19'),
        (5, 2, 8, 'Fear breaks the character’s mind. He falls into a coma for half a week and his memory of the last 2D10 days is erased. After such a traumatic experience, the character likely develops a mental disorder (a Bane worth 2-3 GP). Player and GM should discuss what this might be.'),
        (5, 1, 9, '20+'),
        (5, 2, 9, 'The character dies from sudden cardiac arrest.');